//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery_dl_UI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallery_dl_UI.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gallery-dl Update.
        /// </summary>
        public static string GalleryDlUpdateTitle {
            get {
                return ResourceManager.GetString("GalleryDlUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new version of gallery-dl is available.\n\nInstalled version: {0}\nLatest version: {1}.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation successfully completed.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloads Started.
        /// </summary>
        public static string OperationInit {
            get {
                return ResourceManager.GetString("OperationInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation in progress.
        /// </summary>
        public static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check or add your Pixiv refresh token. Follow the cmd window instructions..
        /// </summary>
        public static string PixivError {
            get {
                return ResourceManager.GetString("PixivError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sleeping....
        /// </summary>
        public static string Sleeping {
            get {
                return ResourceManager.GetString("Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There Were Errors.
        /// </summary>
        public static string ThereWereErrors {
            get {
                return ResourceManager.GetString("ThereWereErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter has changed its authentication system, you now need to add your acount to continue downloading from this platform..
        /// </summary>
        public static string TwitterError {
            get {
                return ResourceManager.GetString("TwitterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL copied correctly.
        /// </summary>
        public static string UrlCopied {
            get {
                return ResourceManager.GetString("UrlCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Urls Added.
        /// </summary>
        public static string UrlsAdded {
            get {
                return ResourceManager.GetString("UrlsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urls to Download.
        /// </summary>
        public static string UrlsToDownload {
            get {
                return ResourceManager.GetString("UrlsToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} URLs with erros.
        /// </summary>
        public static string UrlsWithErrors {
            get {
                return ResourceManager.GetString("UrlsWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait for the download to finish before adding new URLs.
        /// </summary>
        public static string WaitForFinish {
            get {
                return ResourceManager.GetString("WaitForFinish", resourceCulture);
            }
        }
    }
}
